### ISSUE TITLE
The generator failed miserable when I tried to create a standalone component

### ISSUE THREAD

**Issue by kylebuch8** [RHElements/generator-rhelement#59]
First, `yo pfelement` doesn't seem to work anymore. Since the package name is now `@patternfly/generator-pfelement`, you need to use the command `@patternfly/pfelement` to get things to work.

There's an overwrite issue early on in the scaffolding.

![image](https://user-images.githubusercontent.com/330256/73856383-5ff1b800-4803-11ea-9efe-a1c969239c77.png)

Selecting "yes" gives me this error.
```
Error: EISDIR: illegal operation on a directory, open '/Users/kylebuchanan/Desktop/test-component'
```

If I select "no", things proceed but then I start running into issues in the build process.

![image](https://user-images.githubusercontent.com/330256/73856800-02aa3680-4804-11ea-80c2-1311a7144341.png)

Here's a list of missing dev packages:
- gulp-clean
- gulp-sass
- gulp-postcss
- autoprefixer
- gulp-clean-css
- postcss-custom-properties
- rollup-plugin-terser
- rollup-plugin-re

After installing all of the missing dev packages, we run into a gulp issue.

```
/bin/sh: ../../node_modules/.bin/rollup: No such file or directory
```

Line 310 in `./scripts/gulpfile.factory.js` has
```
task("bundle", shell.task("../../node_modules/.bin/rollup -c"));
```

Changing this line to what's below fixes the issue with rollup.

```
task("bundle", shell.task("./node_modules/.bin/rollup -c"));
```

After adjusting all of that and installing the dev packages, the build finally finishes.

Finally, running a dev server doesn't seem to be a dev server available anymore. And if I run an `http-server` on the demo directory, the paths in the components don't work. I think some symlinking needs to happen.

**Comment by castastrophe** [comment]
Propose moving this to the main patternfly-elements repo now that the generator has been migrated.
